### ISSUE TITLE
how to get support set from test dataset without labels?

### ISSUE THREAD

**Issue by fourseven471** [thunlp/HATT-Proto-for-Few-Shot-Relation-Classification#3]
In framework.eval()
->support, query, label = eval_dataset.next_batch(B, N, K, Q, noise_rate=noise_rate)

how to get support set from test dataset without labels?

**Comment by gaotianyu1350** [comment]
The test set of FewRel is reserved for online evaluation and you can refer to the [website](http://www.zhuhao.me/fewrel/). If you have your own test set with no labels, you need to modify the function `next_batch`. I'm not sure the definition of ''without labels''. If you do not have labels for all the instances, you cannot do few-shot since you cannot sample the support set at all.
